const params = new URLSearchParams({
  nome: nome.value,
  rg: rg.value,
  cpf: cpf.value,
  nascimento: nascimento.value,
  endereco: endereco.value,
  numero: numero.value,
  complemento: complemento.value,
  cidade: cidade.value,
  bairro: bairro.value,
  uf: uf.value,
  cep: cep.value,
  telefone: telefone.value,
  email: email.value,
  plano: plano.value,
  valor: valor.value,
  taxaInstalacao: taxaInstalacao.value,
  vencimento: vencimento.value,
  comodato: comodato,
  condRoteador: condRoteador.value,
  condPagamento: condPagamento.value,
  vendedor: vendedor.value,
  observacao: observacao.value,
  score: score.value,
  codigo: codigo.value,
  cor: cor.value
});
